language: java
jdk:
  - oraclejdk8
install:
  - curl 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar' > 'gson-2.8.2.jar'
  - javac -cp gson-2.8.2.jar:. com/linaresdigital/httpservertest/HttpServerTest.java
script:
  - java -cp gson-2.8.2.jar:. com.linaresdigital.httpservertest.HttpServerTest & sleep 2
  - "curl 'http://localhost:8080/' | tee /dev/fd/2 | grep -q 'Aplicación de ejemplo'"
  - "curl 'http://localhost:8080/mal' | tee /dev/fd/2 | grep -q 'Error 404'"
  - kill %1
